package org.khasanof.domainModel.identifiers.simpleIdentifier;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import java.util.UUID;

/**
 * Author: Nurislom
 * <br/>
 * Date: 1/30/2023
 * <br/>
 * Time: 5:23 PM
 * <br/>
 * Package: org.khasanof.domainModel.identifiers
 */
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Entity(name = "simple_identifiers_gen_exm")
public class SimpleIdentifiersGenExample {

    /*
        Simple Identifier
     */
    @Id
    private Integer simpleIdentifier;

    /*
        Generated Identifiers
     */
    @Id
    @GeneratedValue
    private UUID id;

    /*
        IDENTITY Generation

        This type of generation relies on the IdentityGenerator, which expects values
        generated by an identity column in the database. This means they are auto-incremented.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long identityIdentifier;

    /*
        SEQUENCE Generation

        To use a sequence-based id, Hibernate provides the SequenceStyleGenerator class.

        This generator uses sequences if our database supports them. It switches to table generation if they aren't supported.

        In order to customize the sequence name, we can use the @GenericGenerator annotation with SequenceStyleGenerator strategy:
     */
    @Id
    @GeneratedValue
    @GenericGenerator(
            name = "sequence_generator",
            strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @Parameter(name = "sequence_name", value = "user_sequence"),
                    @Parameter(name = "initial_value", value = "4"),
                    @Parameter(name = "increment_value", value = "1")
            }
    )
    private int sequenceIdentifier;

    /*
        TABLE Generation

        The TableGenerator uses an underlying database table that holds segments of identifier generation values.

        Let's customize the table name using the @TableGenerator annotation:
     */
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    @TableGenerator(
            name = "table_generator",
            table = "dep_ids",
            pkColumnName = "seq_id",
            valueColumnName = "seq_value"
    )
    private long tableIdentifier;


    // Go to the README.md file for more information
}

